# Generated by Django 5.2.6 on 2025-09-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN7kLTiwkMphMDqK3qyiyTOBnFQI_q-yInQg&s', null=True, upload_to='category_icons/'),
        ),
    ]
