# Generated by Django 5.2.6 on 2025-09-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category_icons/default.jpg', null=True, upload_to='category_icons/'),
        ),
    ]
