# Generated by Django 5.2.6 on 2025-09-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='income_images/default.jpg', null=True, upload_to='income_images/'),
        ),
    ]
