# Generated by Django 5.2.6 on 2025-09-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='income',
            name='product_name',
        ),
    ]
