# Generated by Django 5.2.6 on 2025-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_expense_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, default='expense_images/default.jpg', null=True, upload_to='expense_images/')),
            ],
        ),
    ]
